"""empty message

Revision ID: 1e4722173fd
Revises: 3f0458fa14b
Create Date: 2015-10-17 17:02:44.558410

"""

# revision identifiers, used by Alembic.
revision = '1e4722173fd'
down_revision = '3f0458fa14b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('item_supplier', sa.String(length=128), nullable=True),
    sa.Column('item_stock_quntity', sa.Integer(), nullable=True),
    sa.Column('item_base_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_item_base_price'), 'items', ['item_base_price'], unique=False)
    op.create_index(op.f('ix_items_item_stock_quntity'), 'items', ['item_stock_quntity'], unique=False)
    op.create_index(op.f('ix_items_item_supplier'), 'items', ['item_supplier'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('item_tags',
    sa.Column('item_id', sa.String(length=16), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('order_date_time', sa.DateTime(), nullable=True),
    sa.Column('order_user_id', sa.String(length=16), nullable=True),
    sa.Column('order_item_id', sa.String(length=16), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('order_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_state'), 'orders', ['order_state'], unique=False)
    op.create_table('order_tags',
    sa.Column('order_id', sa.String(length=16), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_tags')
    op.drop_index(op.f('ix_orders_order_state'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('item_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_items_item_supplier'), table_name='items')
    op.drop_index(op.f('ix_items_item_stock_quntity'), table_name='items')
    op.drop_index(op.f('ix_items_item_base_price'), table_name='items')
    op.drop_table('items')
    ### end Alembic commands ###
