"""empty message

Revision ID: 264add51266
Revises: None
Create Date: 2015-10-17 13:43:33.847845

"""

# revision identifiers, used by Alembic.
revision = '264add51266'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('item_supplier', sa.String(length=128), nullable=True),
    sa.Column('item_stock_quantity', sa.Integer(), nullable=True),
    sa.Column('item_base_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_item_base_price'), 'items', ['item_base_price'], unique=False)
    op.create_index(op.f('ix_items_item_stock_quantity'), 'items', ['item_stock_quantity'], unique=False)
    op.create_index(op.f('ix_items_item_supplier'), 'items', ['item_supplier'], unique=False)
    op.create_table('itemtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemtags_name'), 'itemtags', ['name'], unique=False)
    op.create_table('ordertags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordertags_name'), 'ordertags', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_company', sa.String(length=128), nullable=True),
    sa.Column('user_discount_rate', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_company'), 'users', ['user_company'], unique=False)
    op.create_table('item_tags',
    sa.Column('item_id', sa.String(length=16), nullable=True),
    sa.Column('itemtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['itemtag_id'], ['itemtags.id'], )
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('order_date_time', sa.Integer(), nullable=True),
    sa.Column('order_user_id', sa.String(length=16), nullable=True),
    sa.Column('order_item_id', sa.String(length=16), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('order_state', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_date_time'), 'orders', ['order_date_time'], unique=False)
    op.create_index(op.f('ix_orders_order_quantity'), 'orders', ['order_quantity'], unique=False)
    op.create_index(op.f('ix_orders_order_state'), 'orders', ['order_state'], unique=False)
    op.create_table('order_tags',
    sa.Column('order_id', sa.String(length=16), nullable=True),
    sa.Column('ordertag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['ordertag_id'], ['ordertags.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_tags')
    op.drop_index(op.f('ix_orders_order_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_quantity'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date_time'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('item_tags')
    op.drop_index(op.f('ix_users_user_company'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ordertags_name'), table_name='ordertags')
    op.drop_table('ordertags')
    op.drop_index(op.f('ix_itemtags_name'), table_name='itemtags')
    op.drop_table('itemtags')
    op.drop_index(op.f('ix_items_item_supplier'), table_name='items')
    op.drop_index(op.f('ix_items_item_stock_quantity'), table_name='items')
    op.drop_index(op.f('ix_items_item_base_price'), table_name='items')
    op.drop_table('items')
    ### end Alembic commands ###
