"""empty message

Revision ID: 3f0458fa14b
Revises: None
Create Date: 2015-10-17 16:05:08.902756

"""

# revision identifiers, used by Alembic.
revision = '3f0458fa14b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_company', sa.String(length=128), nullable=True),
    sa.Column('user_discount_rate', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_company'), 'users', ['user_company'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_company'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
