"""empty message

Revision ID: 556bc03ebdc
Revises: None
Create Date: 2015-10-18 01:07:05.969263

"""

# revision identifiers, used by Alembic.
revision = '556bc03ebdc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('item_supplier', sa.String(length=128), nullable=True),
    sa.Column('item_stock_quantity', sa.Integer(), nullable=True),
    sa.Column('item_base_price', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_item_base_price'), 'items', ['item_base_price'], unique=False)
    op.create_index(op.f('ix_items_item_stock_quantity'), 'items', ['item_stock_quantity'], unique=False)
    op.create_index(op.f('ix_items_item_supplier'), 'items', ['item_supplier'], unique=False)
    op.create_index(op.f('ix_items_tags'), 'items', ['tags'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_company', sa.String(length=128), nullable=True),
    sa.Column('user_discount_rate', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_company'), 'users', ['user_company'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('order_date_time', sa.Integer(), nullable=True),
    sa.Column('order_user_id', sa.String(length=16), nullable=True),
    sa.Column('order_item_id', sa.String(length=16), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('order_state', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_date_time'), 'orders', ['order_date_time'], unique=False)
    op.create_index(op.f('ix_orders_order_quantity'), 'orders', ['order_quantity'], unique=False)
    op.create_index(op.f('ix_orders_order_state'), 'orders', ['order_state'], unique=False)
    op.create_index(op.f('ix_orders_tags'), 'orders', ['tags'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tags'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_quantity'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date_time'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_user_company'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_tags'), table_name='items')
    op.drop_index(op.f('ix_items_item_supplier'), table_name='items')
    op.drop_index(op.f('ix_items_item_stock_quantity'), table_name='items')
    op.drop_index(op.f('ix_items_item_base_price'), table_name='items')
    op.drop_table('items')
    ### end Alembic commands ###
