"""empty message

Revision ID: f6cdc699a0
Revises: 1e4722173fd
Create Date: 2015-10-17 17:18:54.836056

"""

# revision identifiers, used by Alembic.
revision = 'f6cdc699a0'
down_revision = '1e4722173fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_stock_quantity', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_item_stock_quantity'), 'items', ['item_stock_quantity'], unique=False)
    op.drop_index('ix_items_item_stock_quntity', table_name='items')
    op.drop_column('items', 'item_stock_quntity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_stock_quntity', sa.INTEGER(), nullable=True))
    op.create_index('ix_items_item_stock_quntity', 'items', ['item_stock_quntity'], unique=False)
    op.drop_index(op.f('ix_items_item_stock_quantity'), table_name='items')
    op.drop_column('items', 'item_stock_quantity')
    ### end Alembic commands ###
